### ISSUE TITLE
运行的时候再GoodsMapper.xml出现BadSqlGrammarException错误，能看一下吗谢谢啦

### ISSUE THREAD

**Issue by huanghe1993** [Manphil/shop#25]
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') 
   
    limit 10' at line 13
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') 
   

    limit 10' at line 13
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')

**Comment by Manphil** [comment]
抱歉，今天才看到，已解决。

**Comment by WangYekun** [comment]
能问下使用avtiveMQ吗？
